const records=[
 {doc:"LP-2024-005",date:"2024. június 08.",upload:"2024. június 09.",iso:"2024-06-08",values:[["Hemoglobin","142","120–160 g/L"],["Vércukor","4.8","3.9–5.6 mmol/L"],["Koleszterin","4.2","3.0–5.2 mmol/L"]]},
 {doc:"LP-2024-004",date:"2024. április 21.",upload:"2024. április 22.",iso:"2024-04-21",values:[["Hemoglobin","139","120–160 g/L"],["Vércukor","5.1","3.9–5.6 mmol/L"],["Koleszterin","4.4","3.0–5.2 mmol/L"]]}
];
const patients=[
 {name:"Kovács Anna",meta:"34 éves • 68 kg • Nő",status:"Engedélyezve",kind:"approved",latest:"2024. június 08.",score:"84 / 100"},
 {name:"Szabó Bence",meta:"42 éves • 81 kg • Férfi",status:"Engedélyezve",kind:"approved",latest:"2024. május 27.",score:"78 / 100"},
 {name:"Tóth Éva",meta:"29 éves • 59 kg • Nő",status:"Jóváhagyásra vár",kind:"pending",latest:"Hozzáférés szükséges",score:"—"}
];
const patientRecords=[...records];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let chart,patientChart,recordsChart,patientRecordsChart,activeRecord=0,selectedPatient=0;
function showView(view){$$(".content-view").forEach(x=>x.classList.add("d-none"));$(`#${view}-view`).classList.remove("d-none");$$(".side-link").forEach(x=>x.classList.toggle("active",x.dataset.view===view));if(view==="records"){renderTable();drawRecordsChart();}if(view==="patient-records"){renderPatientRecords();drawPatientRecordsChart();}}
function openApp(){ $("#auth-view").classList.add("d-none");$("#app-view").classList.remove("d-none");renderPatients();renderRecent();renderTable();drawChart();}
function renderPatients(){let html=patients.map((p,i)=>`<tr data-patient="${i}"><td><span class="avatar patient-avatar">${p.name.split(" ").map(x=>x[0]).join("")}</span><strong>${p.name}</strong><small>${p.meta}</small></td><td>${p.latest}</td><td><span class="status ${p.kind}">${p.kind==="pending"?'<i class="bi bi-hourglass-split"></i>':'<i class="bi bi-check2"></i>'} ${p.status}</span></td><td>${p.score}</td><td><i class="bi bi-chevron-right"></i></td></tr>`).join("");$$("#patients-table").forEach(table=>table.innerHTML=html);$$("[data-patient]").forEach(x=>x.addEventListener("click",()=>openPatient(+x.dataset.patient)));}
function renderRecent(){ $("#recent-results").innerHTML=records.map((r,i)=>`<article class="result-card" data-record="${i}"><div class="doc">${r.doc}</div><div class="result-date"><i class="bi bi-calendar3"></i> ${r.date}</div><span class="status approved"><i class="bi bi-check2"></i> Feldolgozva</span></article>`).join("");$$("[data-record]").forEach(x=>x.addEventListener("click",()=>openEdit(+x.dataset.record)));}
function renderTable(){let q=($("#record-search")?.value||"").toLowerCase();$("#records-table").innerHTML=records.filter(r=>r.doc.toLowerCase().includes(q)).map((r,i)=>`<tr data-record="${i}"><td>${r.doc}</td><td>${r.date}</td><td>${r.upload}</td><td><span class="status approved"><i class="bi bi-check2"></i> Feldolgozva</span></td><td><i class="bi bi-chevron-right"></i></td></tr>`).join("");$$("#records-table [data-record]").forEach(x=>x.addEventListener("click",()=>openEdit(+x.dataset.record)));}
function renderPatientRecords(){let q=($("#patient-record-search")?.value||"").toLowerCase();$("#patient-records-table").innerHTML=patientRecords.filter(r=>r.doc.toLowerCase().includes(q)).map(r=>`<tr><td><strong>${r.doc}</strong></td><td>${r.date}</td><td>${r.upload}</td><td><span class="status approved"><i class="bi bi-check2"></i> Feldolgozva</span></td><td><i class="bi bi-eye"></i></td></tr>`).join("");}
function openPatient(i){selectedPatient=i;if(patients[i].kind==="pending"){new bootstrap.Modal($("#requestModal")).show();return;}showView("patient");$("#patient-name").textContent=patients[i].name;$("#patient-meta").textContent=patients[i].meta;$("#patient-latest").textContent=patients[i].latest;drawPatientChart();}
function openEdit(i){activeRecord=i;let r=records[i];showView("edit");$("#edit-title").textContent=r.doc;$("#edit-doc").value=r.doc;$("#edit-date").value=r.iso;$("#edit-upload").value=r.iso;$("#values-list").innerHTML=r.values.map(v=>`<div class="value-row"><div><strong>${v[0]}</strong><br><small>${v[2]}</small></div><input class="form-control" value="${v[1]}"><small>${v[2].split(" ")[1]||""}</small></div>`).join("");}
function drawChart(metric="health"){let data=metric==="hemoglobin"?[76,79,77,81,84]:metric==="glucose"?[80,78,82,80,83]:metric==="cholesterol"?[69,72,75,78,81]:[72,76,79,81,84];$("#current-score").textContent=`${data.at(-1)} / 100`;chart=createTrend($("#health-chart"),chart,data);}
function drawPatientChart(){let canvas=$("#patient-chart");if(!canvas)return;if(patientChart)patientChart.destroy();patientChart=new Chart(canvas,{type:"line",data:{labels:["2023. okt.","2023. dec.","2024. febr.","2024. ápr.","2024. jún."],datasets:[{data:[72,76,79,81,84],fill:true,borderColor:"#4fc4ad",backgroundColor:"rgba(87,199,175,.12)",borderWidth:2.5,tension:.4,pointRadius:4}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{min:50,max:100}}}});}
function createTrend(canvas,instance,data){if(!canvas)return instance&&instance.destroy();if(instance)instance.destroy();return new Chart(canvas,{type:"line",data:{labels:["2023. okt.","2023. dec.","2024. febr.","2024. ápr.","2024. jún."],datasets:[{data,fill:true,borderColor:"#4fc4ad",backgroundColor:"rgba(87,199,175,.12)",borderWidth:2.5,tension:.4,pointRadius:4,pointBackgroundColor:"#fff",pointBorderColor:"#4fc4ad",pointBorderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{min:50,max:100,grid:{color:"#edf2f3"},ticks:{color:"#a1acb9",stepSize:10}}}}});}
function drawRecordsChart(){recordsChart=createTrend($("#records-chart"),recordsChart,[72,76,79,81,84]);}
function drawPatientRecordsChart(){patientRecordsChart=createTrend($("#patient-records-chart"),patientRecordsChart,[72,76,79,81,84]);}
$$("[data-auth-tab]").forEach(btn=>btn.addEventListener("click",()=>{let register=btn.dataset.authTab==="register";$$(".auth-tab").forEach(x=>x.classList.toggle("active",x===btn));$("#login-form").classList.toggle("d-none",register);$("#register-form").classList.toggle("d-none",!register);}));$("#login-form").addEventListener("submit",e=>{e.preventDefault();openApp()});$("#register-form").addEventListener("submit",e=>{e.preventDefault();openApp()});$$(".google-btn").forEach(x=>x.addEventListener("click",openApp));$$(".side-link[data-view],.text-btn[data-view],.back-button").forEach(x=>x.addEventListener("click",()=>showView(x.dataset.view)));$$("[data-profile]").forEach(x=>x.addEventListener("click",()=>new bootstrap.Modal($("#profileModal")).show()));$(".logout-btn").addEventListener("click",()=>{$("#app-view").classList.add("d-none");$("#auth-view").classList.remove("d-none")});$("#metric-select").addEventListener("change",e=>drawChart(e.target.value));$("#record-search").addEventListener("input",renderTable);$("#patient-record-search").addEventListener("input",renderPatientRecords);$("#save-record").addEventListener("click",()=>{records[activeRecord].doc=$("#edit-doc").value;renderRecent();showView("records")});$("#approve-request").addEventListener("click",()=>{patients[selectedPatient].kind="approved";patients[selectedPatient].status="Engedélyezve";patients[selectedPatient].latest="Nincs még eredmény";patients[selectedPatient].score="—";bootstrap.Modal.getInstance($("#requestModal")).hide();renderPatients()});
const newResultModal=new bootstrap.Modal($("#newResultModal"));$("#new-result-btn").addEventListener("click",()=>newResultModal.show());$("#new-result-form").addEventListener("submit",e=>{e.preventDefault();records.unshift({doc:$("#new-doc").value,date:$("#new-date").value,upload:$("#new-upload").value,iso:$("#new-date").value,values:[["Hemoglobin","—","120–160 g/L"],["Vércukor","—","3.9–5.6 mmol/L"],["Koleszterin","—","3.0–5.2 mmol/L"]]});newResultModal.hide();renderRecent();renderTable()});
