const records=[
 {doc:"LP-2024-005",date:"2024. június 08.",upload:"2024. június 09.",iso:"2024-06-08",values:[["Hemoglobin","142","120–160 g/L"],["Vércukor","4.8","3.9–5.6 mmol/L"],["Koleszterin","4.2","3.0–5.2 mmol/L"]]},
 {doc:"LP-2024-004",date:"2024. április 21.",upload:"2024. április 22.",iso:"2024-04-21",values:[["Hemoglobin","139","120–160 g/L"],["Vércukor","5.1","3.9–5.6 mmol/L"],["Koleszterin","4.4","3.0–5.2 mmol/L"]]},
 {doc:"LP-2024-003",date:"2024. február 15.",upload:"2024. február 16.",iso:"2024-02-15",values:[["Hemoglobin","145","120–160 g/L"],["Vércukor","4.6","3.9–5.6 mmol/L"],["Koleszterin","4.1","3.0–5.2 mmol/L"]]},
 {doc:"LP-2023-002",date:"2023. december 03.",upload:"2023. december 04.",iso:"2023-12-03",values:[["Hemoglobin","137","120–160 g/L"],["Vércukor","5.3","3.9–5.6 mmol/L"],["Koleszterin","4.7","3.0–5.2 mmol/L"]]},
 {doc:"LP-2023-001",date:"2023. október 18.",upload:"2023. október 19.",iso:"2023-10-18",values:[["Hemoglobin","134","120–160 g/L"],["Vércukor","5.0","3.9–5.6 mmol/L"],["Koleszterin","4.9","3.0–5.2 mmol/L"]]}
];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let chart, activeRecord;
function showView(view){$$(".content-view").forEach(x=>x.classList.add("d-none"));$(`#${view}-view`).classList.remove("d-none");$$(".side-link").forEach(x=>x.classList.toggle("active",x.dataset.view===view));if(view==="records")renderTable();}
function openApp(){ $("#auth-view").classList.add("d-none");$("#app-view").classList.remove("d-none");renderRecent();renderTable();drawChart(); }
function renderRecent(){ $("#recent-results").innerHTML=records.map((r,i)=>`<article class="result-card" data-record="${i}"><div class="doc">${r.doc}</div><div class="result-date"><i class="bi bi-calendar3"></i> ${r.date}</div><span class="status"><i class="bi bi-check2"></i> Feldolgozva</span></article>`).join("");$$("[data-record]").forEach(x=>x.addEventListener("click",()=>openEdit(+x.dataset.record)));}
function renderTable(){let q=($("#record-search")?.value||"").toLowerCase();$("#records-table").innerHTML=records.filter(r=>r.doc.toLowerCase().includes(q)).map((r,i)=>`<tr data-record="${i}"><td>${r.doc}</td><td>${r.date}</td><td>${r.upload}</td><td><span class="status"><i class="bi bi-check2"></i> Feldolgozva</span></td><td><i class="bi bi-chevron-right"></i></td></tr>`).join("");$$("#records-table [data-record]").forEach(x=>x.addEventListener("click",()=>openEdit(+x.dataset.record)));}
function openEdit(i){activeRecord=i;let r=records[i];showView("edit");$("#edit-title").textContent=r.doc;$("#edit-doc").value=r.doc;$("#edit-date").value=r.iso;$("#edit-upload").value=r.iso;$("#values-list").innerHTML=r.values.map(v=>`<div class="value-row"><div><strong>${v[0]}</strong><br><small>${v[2]}</small></div><input class="form-control" value="${v[1]}"><small>${v[2].split(" ")[1]||""}</small></div>`).join("");}
function drawChart(metric="health"){let data=metric==="hemoglobin"?[76,79,77,81,84]:metric==="glucose"?[80,78,82,80,83]:metric==="cholesterol"?[69,72,75,78,81]:[72,76,79,81,84];$("#current-score").textContent=`${data.at(-1)} / 100`;if(chart)chart.destroy();chart=new Chart($("#health-chart"),{type:"line",data:{labels:["2023. okt.","2023. dec.","2024. febr.","2024. ápr.","2024. jún."],datasets:[{data,fill:true,borderColor:"#4fc4ad",backgroundColor:"rgba(87,199,175,.12)",borderWidth:2.5,tension:.4,pointRadius:4,pointBackgroundColor:"#fff",pointBorderColor:"#4fc4ad",pointBorderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>` ${c.raw} / 100`}}},scales:{x:{grid:{display:false},ticks:{display:false}},y:{min:50,max:100,grid:{color:"#edf2f3"},ticks:{color:"#a1acb9",font:{size:10},stepSize:10}}}}});}
function openChat(){new bootstrap.Modal($("#chatModal")).show();}
$$("[data-auth-tab]").forEach(btn=>btn.addEventListener("click",()=>{let register=btn.dataset.authTab==="register";$$(".auth-tab").forEach(x=>x.classList.toggle("active",x===btn));$("#login-form").classList.toggle("d-none",register);$("#register-form").classList.toggle("d-none",!register);}));
$("#login-form").addEventListener("submit",e=>{e.preventDefault();openApp()});$("#register-form").addEventListener("submit",e=>{e.preventDefault();openApp()});
$$(".google-btn").forEach(x=>x.addEventListener("click",openApp));$$(".side-link[data-view],.text-btn[data-view],.back-button").forEach(x=>x.addEventListener("click",()=>showView(x.dataset.view)));
$$("[data-profile]").forEach(x=>x.addEventListener("click",()=>new bootstrap.Modal($("#profileModal")).show()));$$("[data-chat]").forEach(x=>x.addEventListener("click",openChat));
$(".logout-btn").addEventListener("click",()=>{$("#app-view").classList.add("d-none");$("#auth-view").classList.remove("d-none")});$("#metric-select").addEventListener("change",e=>drawChart(e.target.value));$("#record-search").addEventListener("input",renderTable);
$("#save-record").addEventListener("click",()=>{records[activeRecord].doc=$("#edit-doc").value;records[activeRecord].date=$("#edit-date").value;records[activeRecord].upload=$("#edit-upload").value;renderRecent();showView("records")});
$("#chat-send").addEventListener("click",sendMessage);$("#chat-input").addEventListener("keydown",e=>{if(e.key==="Enter")sendMessage()});function sendMessage(){let input=$("#chat-input"),text=input.value.trim();if(!text)return;$("#chat-messages").insertAdjacentHTML("beforeend",`<div class="chat-message user">${text}</div><div class="chat-message bot">Köszönöm a kérdésed! Ez egy szimulált válasz. Az eredményeid értelmezéséhez és személyre szabott tanácshoz mindig egyeztess kezelőorvosoddal.</div>`);input.value="";}
document.addEventListener("click",e=>{let p=e.target.closest(".show-password");if(p){let input=$("#password");input.type=input.type==="password"?"text":"password";p.innerHTML=`<i class="bi bi-eye${input.type==="password"?"":"-slash"}"></i>`}});
const inputMethodModal=new bootstrap.Modal($("#inputMethodModal")),manualInputModal=new bootstrap.Modal($("#manualInputModal")),cameraInputModal=new bootstrap.Modal($("#cameraInputModal"));
function openInputModal(modal){$("#inputMethodModal").addEventListener("hidden.bs.modal",()=>modal.show(),{once:true});inputMethodModal.hide();}
$("#new-result-btn").addEventListener("click",()=>inputMethodModal.show());
$("#manual-input-btn").addEventListener("click",()=>openInputModal(manualInputModal));
$("#camera-input-btn").addEventListener("click",()=>openInputModal(cameraInputModal));
$("#manual-input-form").addEventListener("submit",e=>{e.preventDefault();let date=$("#manual-date").value,upload=$("#manual-upload").value;records.unshift({doc:$("#manual-doc").value,date,upload,iso:date,values:[["Hemoglobin",$("#manual-hemoglobin").value,"120–160 g/L"],["Vércukor",$("#manual-glucose").value,"3.9–5.6 mmol/L"],["Koleszterin",$("#manual-cholesterol").value,"3.0–5.2 mmol/L"]]});manualInputModal.hide();renderRecent();renderTable();});
