const requests=[
 {id:"REQ-2024-018",name:"Dr. Varga Júlia",initials:"VJ",specialty:"Kardiológia",email:"julia.varga@medmail.hu",license:"O-45821",submitted:"2024. június 11.",status:"Feldolgozásra vár",documents:["varga-license.svg","varga-id.svg"]},
 {id:"REQ-2024-017",name:"Dr. Fekete Márton",initials:"FM",specialty:"Háziorvostan",email:"marton.fekete@medmail.hu",license:"O-39204",submitted:"2024. június 09.",status:"Feldolgozásra vár",documents:["fekete-license.svg","fekete-id.svg"]}
];
const archivedRequests=[];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let selected=0,currentDocument=0;
function showView(view){$$(".content-view").forEach(x=>x.classList.add("d-none"));$(`#${view}-view`).classList.remove("d-none");if(view==="requests")renderRequests();if(view==="archive")renderArchive();}
function statusClass(status){return status==="Jóváhagyva"?"approved":status==="Elutasítva"?"rejected":"";}
function renderRequests(){let html=requests.map((r,i)=>`<tr data-request="${i}"><td><span class="avatar request-avatar">${r.initials}</span><strong>${r.name}</strong><small>${r.specialty}</small></td><td>${r.id}</td><td>${r.submitted}</td><td><span class="request-status ${statusClass(r.status)}">${r.status}</span></td><td><i class="bi bi-chevron-right"></i></td></tr>`).join("");$("#requests-table").innerHTML=html||'<tr><td colspan="5" class="archive-empty">Nincs feldolgozásra váró kérelem.</td></tr>';$("[data-pending-count]").textContent=requests.length;$$("[data-request]").forEach(row=>row.addEventListener("click",()=>openRequest(+row.dataset.request)));}
function renderArchive(){let html=archivedRequests.map((r,i)=>`<tr><td><span class="avatar request-avatar">${r.initials}</span><strong>${r.name}</strong><small>${r.specialty}</small></td><td>${r.id}</td><td>${r.submitted}</td><td><span class="request-status ${statusClass(r.status)}">${r.status}</span></td><td>${r.processed}</td></tr>`).join("");$("#archive-table").innerHTML=html||'<tr><td colspan="5" class="archive-empty"><i class="bi bi-archive"></i>Az archívum még üres.</td></tr>';}
function openRequest(index){selected=index;currentDocument=0;let r=requests[index];showView("detail");$("#detail-name").textContent=r.name;$("#detail-specialty").textContent=r.specialty;$("#detail-email").textContent=r.email;$("#detail-license").textContent=r.license;$("#detail-id").textContent=r.id;$("#detail-submitted").textContent=r.submitted;renderDocument();}
function renderDocument(){let r=requests[selected];$("#document-image").src=r.documents[currentDocument];$("#document-image").alt=`${r.name} ${currentDocument===0?"működési engedélye":"személyazonosítója"}`;$$(".document-tab").forEach((tab,i)=>tab.classList.toggle("active",i===currentDocument));}
function updateRequest(status){let request=requests.splice(selected,1)[0];request.status=status;request.processed="2024. június 12.";archivedRequests.unshift(request);$(".archive-count").textContent=archivedRequests.length;showView("requests");}
$("#login-form").addEventListener("submit",e=>{e.preventDefault();$("#auth-view").classList.add("d-none");$("#app-view").classList.remove("d-none");renderRequests()});$$(".google-btn").forEach(x=>x.addEventListener("click",()=>{$("#auth-view").classList.add("d-none");$("#app-view").classList.remove("d-none");renderRequests()}));$("#approve-request").addEventListener("click",()=>updateRequest("Jóváhagyva"));$("#reject-request").addEventListener("click",()=>updateRequest("Elutasítva"));$(".back-button").addEventListener("click",()=>showView("requests"));$$(".document-tab").forEach((tab,i)=>tab.addEventListener("click",()=>{currentDocument=i;renderDocument()}));$(".logout-btn").addEventListener("click",()=>{$("#app-view").classList.add("d-none");$("#auth-view").classList.remove("d-none")});$$("[data-view]").forEach(x=>x.addEventListener("click",()=>showView(x.dataset.view)));
